name: First interaction

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master  ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Greetings for PR and issues
      uses: actions/first-interaction@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue!!'
        pr-message: 'Hello @${{ github.actor }} , thank you for submitting a pull request!!'
